name: Deploy API on Main Branch

on:
  push:
    branches:
      - main
    paths:
      - "tournament-api/**"
      
defaults:
  run:
    working-directory: ./tournament-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy API
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a tournament-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
